---
- name: Ensure shared env-files directory exists
  ansible.builtin.file:
    path: "{{ authentik_env_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0775"

- name: Ensure Authentik shared storage directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0775"
  loop:
    - /mnt/proxmox_swarm_data/authentik
    - /mnt/proxmox_swarm_data/authentik/media
    - /mnt/proxmox_swarm_data/authentik/custom-templates
    - /mnt/proxmox_swarm_data/authentik/certs

- name: Ensure Authentik directories are writable on NFS
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
    recurse: true
  loop:
    - /mnt/proxmox_swarm_data/authentik/media
    - /mnt/proxmox_swarm_data/authentik/custom-templates
    - /mnt/proxmox_swarm_data/authentik/certs

- name: Render Authentik env file from Vaultwarden
  ansible.builtin.template:
    src: "authentik.env.j2"
    dest: "{{ authentik_env_file }}"
    owner: root
    group: root
    mode: "0644"
