http:
  routers:
    esphome:
      rule: "Host(`esphome.tuxito.be`)"
      entryPoints:
        - websecure
      service: esphome
      tls:
        certResolver: letsencrypt
        domains:
          - main: "tuxito.be"
            sans:
              - "*.tuxito.be"

  services:
    esphome:
      loadBalancer:
        servers:
          - url: "http://192.168.10.100:6052"
