http:
  routers:
    portainer:
      rule: "Host(`portainer.tuxito.be`)"
      entryPoints:
        - websecure
      service: portainer-service
      tls:
        certResolver: letsencrypt
        domains:
          - main: "tuxito.be"
            sans:
              - "*.tuxito.be"

  services:
    portainer-service:
      loadBalancer:
        servers:
          - url: "https://192.168.10.30:9433"
        serversTransport: portainer-transport

  serversTransports:
    portainer-transport:
      insecureSkipVerify: true # Required because Proxmox uses self-signed cert
