http:
  routers:
    proxmox:
      rule: "Host(`proxmox.tuxito.be`)"
      entryPoints:
        - websecure
      service: proxmox-service
      tls:
        certResolver: letsencrypt
        domains:
          - main: "tuxito.be"
            sans:
              - "*.tuxito.be"

  services:
    proxmox-service:
      loadBalancer:
        servers:
          - url: "https://192.168.10.11:8006"
        serversTransport: proxmox-transport

  serversTransports:
    proxmox-transport:
      insecureSkipVerify: true # Required because Proxmox uses self-signed cert
