services:
  esphome:
    image: ghcr.io/esphome/esphome
    container_name: esphome
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
      - ESPHOME_DASHBOARD_USE_PING=true
    volumes:
      - /mnt/proxmox_swarm_data/esphome/:/config:rw
      - esphome_cache:/cache:rw
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    labels:
      - "homepage.group=Development Tools"
      - "homepage.name=EspHome"
      - "homepage.icon=esphome.png"
      - "homepage.href=https://esphome.tuxito.be"
      - "homepage.description=ESP Device Manager"
      - "shepherd.enable=true"
  music-assistant-server:
    image: ghcr.io/music-assistant/server:latest # <<< Desired release version here (or use beta to get the latest beta version)
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - /mnt/proxmox_swarm_data/music-assistant:/data/
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info

volumes:
  esphome_cache:
