services:
  dockhand:
    image: fnsys/dockhand:latest
    env_file:
      - /mnt/proxmox_swarm_data/env-files/dockhand.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/proxmox_swarm_data/dockhand:/app/data:rw
    networks:
      - proxy
      - dockhand_internal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.50"
          memory: "2G"
        reservations:
          cpus: "0.50"
          memory: "512M"
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      labels:
        - "homepage.group=Infrastructure"
        - "homepage.name=Dockhand"
        - "homepage.icon=dockhand.png"
        - "homepage.href=https://dockhand.tuxito.be"
        - "homepage.description=Docker & Swarm Management"
        - "traefik.enable=true"
        - "traefik.http.routers.dockhand.rule=Host(`dockhand.tuxito.be`)"
        - "traefik.http.routers.dockhand.entrypoints=websecure"
        - "traefik.http.routers.dockhand.tls.certresolver=letsencrypt"
        - "traefik.http.services.dockhand.loadbalancer.server.port=5173"
        - "traefik.swarm.network=proxy"
        - "shepherd.enable=true"

networks:
  proxy:
    external: true
  dockhand_internal:
    driver: overlay
    attachable: true
