version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    networks:
      - traefik_public
      - default
    env_file:
      - /mnt/proxmox_swarm_data/env-files/vaultwarden.env
    secrets:
      - vaultwarden_admin_token
    volumes:
      - vaultwarden_data:/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1.00"
          memory: "1G"
        reservations:
          cpus: "0.25"
          memory: "256M"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "homepage.group=Security"
        - "homepage.name=Vaultwarden"
        - "homepage.icon=vaultwarden.png"
        - "homepage.href=https://vault.tuxito.be"
        - "homepage.description=Password Manager"
        - "traefik.enable=true"
        # Main web UI
        - "traefik.http.routers.vaultwarden.rule=Host(`vault.tuxito.be`)"
        - "traefik.http.routers.vaultwarden.entrypoints=websecure"
        - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
        - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true

volumes:
  vaultwarden_data:
    driver: local

secrets:
  vaultwarden_admin_token:
    external: true
