all:
  children:
    proxmox_plex_host:
      hosts:
        proxmox-3:
          ansible_host: 192.168.10.13
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

