services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    env_file:
      - /mnt/proxmox_swarm_data/env-files/cloudflared.env
    labels:
      - "shepherd.enable=true"
    networks:
      - cloudflared

networks:
  cloudflared:
    driver: bridge

