services:
  homepage:
    # Example; https://pastebin.com/u/gladiator30/1/GnZWeXEy
    image: ghcr.io/gethomepage/homepage:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.00"
          memory: "1G"
        reservations:
          cpus: "0.25"
          memory: "256M"
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homepage.rule=Host(`homepage.tuxito.be`)"
        - "traefik.http.routers.homepage.entrypoints=websecure"
        - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"
        - "traefik.http.services.homepage.loadbalancer.server.port=3000"
        - "traefik.swarm.network=proxy"
        - "shepherd.enable=true"
    volumes:
      - /mnt/proxmox_swarm_data/homepage:/app/config
      - /mnt/proxmox_swarm_data/homepage/images:/app/public/images:ro
      - /mnt/proxmox_swarm_data:/mnt/proxmox_swarm_data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.tuxito.be
    networks:
      - proxy

networks:
  proxy:
    external: true
