# cloudflared-stack.yml
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    networks:
      - cloudflared
    env_file:
      - /mnt/proxmox_swarm_data/env-files/cloudflared.env
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s

networks:
  cloudflared:
    external: true
