networks:
  traefik_public:
    external: true

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    hostname: plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - traefik_public
    env_file:
      - /mnt/proxmox_swarm_data/env-files/plex.env
    volumes:
      - plex_config:/config
      - /mnt/nfs/media-nas/movies:/media/movies
      - /mnt/nfs/media-nas/tv:/media/tv
      - /mnt/nfs/media-nas/music:/media/music
      - /mnt/nfs/media-nas/cartoons:/media/cartoons
      - /mnt/nfs/media-nas/comedy:/media/comedy
      - /mnt/nfs/media-nas/audiobooks:/media/audiobooks
      - /mnt/nfs/media-nas/comics:/media/comics
    tmpfs:
      - /transcode:rw,size=8g
    devices:
      - /dev/dri:/dev/dri # Intel Arc GPU passthrough for hardware transcoding
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.id == m6n99yi7ltmxplvpni79dstx4 # Pin to swarm-worker-w1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "homepage.group=Media"
        - "homepage.name=Plex"
        - "homepage.icon=plex.png"
        - "homepage.href=https://plex.tuxito.be"
        - "homepage.description=Media Server"
        - "traefik.enable=true"
        - "traefik.http.routers.plex.rule=Host(`plex.tuxito.be`)"
        - "traefik.http.routers.plex.entrypoints=websecure"
        - "traefik.http.routers.plex.tls.certresolver=letsencrypt"
        - "traefik.http.services.plex.loadbalancer.server.port=32400"
        - "traefik.swarm.network=traefik_public"

volumes:
  plex_config:
    driver: local
