version: "3.9"

networks:
  portainer_net:
    driver: overlay
    attachable: true

services:
  agent:
    image: portainer/agent:latest
    networks:
      - portainer_net
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - portainer_net
    ports:
      - "9443:9443" # UI HTTPS
      - "9000:9000" # UI HTTP (optional, can remove later)
    volumes:
      - /mnt/nfs/portainer:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
