version: "3.9"

networks:
  portainer_net:
    driver: overlay
    attachable: true
  proxy:
    external: true

services:
  agent:
    image: portainer/agent:latest
    networks:
      - portainer_net
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /mnt/proxmox_swarm_data:/mnt/proxmox_swarm_data:ro
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - portainer_net
      - proxy
    volumes:
      - /mnt/proxmox_swarm_data/portainer:/data
      - /mnt/proxmox_swarm_data:/mnt/proxmox_swarm_data:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "homepage.group=Infrastructure"
        - "homepage.name=Portainer"
        - "homepage.icon=portainer.png"
        - "homepage.href=https://portainer.tuxito.be"
        - "homepage.description=Docker Management UI"
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.tuxito.be`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.docker.network=proxy"
